apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictions
  labels:
    app: predictions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictions
  template:
    metadata:
      labels:
        app: predictions
    spec:
      containers:
        - name: predictions
          image: localhost:5000/predictions:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

