apiVersion: v1
kind: Service
metadata:
  name: predictions
  labels:
    app: predictions
spec:
  selector:
    app: predictions
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP

